### ISSUE TITLE
Please add example

### ISSUE THREAD

**Issue by chanif** [gcaglion/Forecaster#1]
could you add example for using this code in mq4 or mq5 please . . . thanks in advance

**Comment by gcaglion** [comment]
I haven't updated this in a while, but it can give you an idea.

[MyForecast.mq4.txt](https://github.com/gcaglion/Forecaster/files/786014/MyForecast.mq4.txt)

**Comment by chanif** [comment]
i'm beginner in c++ trying to code my first EA with AI, and i found the code you wrote is the best example i can find. your example is very helpful for me. i really appreciate your help. thanks a ton
